#CONFIG_APP__PORT
app_port: 8000
#CONFIG_DB
db:
  #CONFIG_DB_HOST
  host: "127.0.0.1"
  #CONFIG_DB_PORT
  port: 5432
  #CONFIG_DB_USER
  user: ""
  #CONFIG_DB_PASSWORD
  password: ""
  #CONFIG_DB_NAME
  name: ""