name: zero2prod

services:
  db:
    image: 'postgres'
    command: '-N 1000'
    container_name: ${PG_CONTAINER_NAME:-postgres}
    ports:
      - ${PG_PORT:-5432}:5432
    volumes:
      - ./data:/var/lib/postgresql/
      - ./scripts/.init.sh:/docker-entrypoint-initdb.d/init.sh
    environment:
      - POSTGRES_USER=${PG_SUPERUSER:-postgres}
      - POSTGRES_PASSWORD=${PG_SUPERUSER_PWD:-somepass}
      - CONFIG_DB_NAME=${CONFIG_DB_NAME:-newsletter}
      - CONFIG_DB_USER=${CONFIG_DB_USER:-docker}
      - CONFIG_DB_PASSWORD=${CONFIG_DB_PASSWORD:-docker}