#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $CONFIG_DB_USER with PASSWORD '$CONFIG_DB_PASSWORD';
	CREATE DATABASE $CONFIG_DB_NAME;

	ALTER USER $CONFIG_DB_USER CREATEDB;
EOSQL