#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	CREATE USER $CONFIG_DB_USER with PASSWORD '$CONFIG_DB_PASSWORD';
	CREATE DATABASE $CONFIG_DB_NAME OWNER $CONFIG_DB_USER;

	GRANT ALL PRIVILEGES ON DATABASE $CONFIG_DB_NAME TO $CONFIG_DB_USER;
EOSQL